[package]
name = "debug-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0.12"
tree-ds = { version = "0.1", features = ["serde", "auto_id"] }
