name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    if: github.event.repository.default_branch == 'main'

  build:
    uses: ./.github/workflows/build.yaml
    needs: check

  test:
    uses: ./.github/workflows/test.yaml
    needs: build

  create-release:
    runs-on: ubuntu-latest
    needs: [check, build, test]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-artifacts/x86_64-unknown-linux-gnu-binary/debug-tree
            release-artifacts/x86_64-pc-windows-msvc-binary/debug-tree.exe
            release-artifacts/aarch64-apple-darwin-binary/debug-tree
          generate_release_notes: true
          draft: false
